[font]
size = 22.0

[font.bold]
family = "Consolas"
style = "Bold"

[font.bold_italic]
family = "Consolas"
style = "Bold Italic"

[font.italic]
family = "Consolas"
style = "Italic"

[font.normal]
family = "Consolas"
style = "Regular"

# Window opacity as a floating point number from `0.0` to `1.0`.
# The value `0.0` is completely transparent and `1.0` is opaque.
[window]
opacity = 0.8


